global using Masuit.Tools;
global using NewLife.Caching;
global using NewLife.Serialization;
global using EasyPlc.Core;
global using SimpleRedis;
global using Furion;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.Extensions.DependencyInjection;